def handle_data_error():
    pass
